"""Typing protocol shared by console and GUI dashboard implementations."""

from __future__ import annotations

from typing import Any, Mapping, Protocol, Sequence

from model.entities import (
    AnalysisConfiguration,
    DistanceTimeSeries,
    EncounterGeometry2D,
    EncounterResult,
    SpacecraftState,
)


class DashboardPresenter(Protocol):
    """Surface area required by `DashboardController` for any dashboard view."""

    def set_controller(self, controller: Any) -> None: ...

    def set_alert_table_sort(self, column: str, descending: bool) -> None: ...

    def get_alert_table_sort(self) -> tuple[str, bool]: ...

    def show(self) -> None: ...

    def display_error(self, message: str) -> None: ...

    def display_catalog_count(self, count: int) -> None: ...

    def display_spacecraft_parameters(self, state: SpacecraftState) -> None: ...

    def display_analysis_configuration(self, config: AnalysisConfiguration) -> None: ...

    def refresh_alert_table(self, rows: list[EncounterResult]) -> None: ...

    def refresh_timeline(self, events: list[EncounterResult]) -> None: ...

    def refresh_distance_plots(self, series_by_id: Mapping[str, DistanceTimeSeries]) -> None: ...

    def refresh_encounter_geometry(self, geometries: Sequence[EncounterGeometry2D]) -> None: ...

    def on_export_csv_requested(self, path: str) -> None: ...

    def on_run_analysis_requested(self) -> None: ...
